// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmvhnwgbclrnkckzkpbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indtdmhud2diY2xybmtja3prcGJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3OTU2MzQsImV4cCI6MjA1MjM3MTYzNH0.oO4bCVY4Yg9Uvcw4YoRAzuHlYLe0thNh5O2JtQtR5h0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);